### ISSUE TITLE
Pip install: Syntax Error

### ISSUE THREAD

**Issue by tokejepsen** [spotify/pythonflow#15]
**Reproducible**

1. Install pythonflow with pip.
2. Run first example in docs:

```python
import pythonflow as pf

with pf.Graph() as graph:
    a = pf.constant(4)
    b = pf.constant(38)
    x = a + b
```
```python
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/pythonflow_testing.py", line 1, in <module>
    import pythonflow as pf
  File "C:\Users\admin\miniconda\envs\pythonflow\lib\site-packages\pythonflow\__init__.py", line 18, in <module>
    from .core import *
  File "C:\Users\admin\miniconda\envs\pythonflow\lib\site-packages\pythonflow\core.py", line 121
    def __call__(self, fetches, context=None, *, callback=None, **kwargs):
                                               ^
SyntaxError: invalid syntax
```

**Comment by tokejepsen** [comment]
Ahh, I think I know what it going on here. Python 3 is required :)

This probably needs a mention in the docs. Or maybe I missed it somewhere?

**Comment by tillahoffmann** [comment]
Yes, we require python 3. I will close this for now (with updated docs and installation in b4775dc), but we are open to contributions to back port to python 2.

**Comment by tokejepsen** [comment]
Cool, thanks for that:-)

Will probably look at porting back, if my prototypes are successful.

**Comment by tillahoffmann** [comment]
Great! Let me know when you start the back port and I'm happy to help out.
