### ISSUE TITLE
ZeroMQ dependency

### ISSUE THREAD

**Issue by tokejepsen** [spotify/pythonflow#16]
I was wondering whether it would be possible to have ZeroMQ as an optional dependency for distributed processing?

In the industry (vfx and animation) I'm interesting in using pythonflow, ZeroMQ is hard to distribute because of the tools we use.
Further we would probably look at using other processing distribution systems, such as using render manager like [Thinkbox](https://deadline.thinkboxsoftware.com/).

**Comment by tillahoffmann** [comment]
Good call, that *should* have been an optional dependency.

**Comment by tokejepsen** [comment]
Nice, excellent quick work:-)
