### ISSUE TITLE
graph function call error

### ISSUE THREAD

**Issue by leepand** [spotify/pythonflow#4]
hi, I use the example code as follow and got error.
>>> import pythonflow as pf
>>>
>>>
>>> with pf.Graph() as graph:
...     a = pf.constant(4)
...     b = pf.constant(38)
...     x = a + b
...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/leepand/Downloads/BigRLab_APIs/flask_lab/pythonflow/pythonflow/core.py", line 329, in __add__
    return add(self, other, graph=self.graph)
  File "/Users/leepand/Downloads/BigRLab_APIs/flask_lab/pythonflow/pythonflow/core.py", line 480, in _wrapper
    return func_op(target, *args, **kwargs_inner, **kwargs)
  File "/Users/leepand/Downloads/BigRLab_APIs/flask_lab/pythonflow/pythonflow/core.py", line 458, in __init__
    super(func_op, self).__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'graph'

**Comment by tillahoffmann** [comment]
@leepand, thanks for flagging the issue. Unfortunately, I cannot reproduce it here:

```
docker run --rm -it python:3 bash
root@377dc229f98b:/# pip install pythonflow
Collecting pythonflow
  Downloading pythonflow-0.1.tar.gz
Building wheels for collected packages: pythonflow
  Running setup.py bdist_wheel for pythonflow ... done
  Stored in directory: /root/.cache/pip/wheels/e7/31/ff/97b76c74b8531673299abfa1973870a27bc4498ef5d3745f1f
Successfully built pythonflow
Installing collected packages: pythonflow
Successfully installed pythonflow-0.1
root@377dc229f98b:/# python
Python 3.6.2 (default, Jul 24 2017, 19:47:39) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythonflow as pf
>>> with pf.Graph() as graph:
...     a = pf.constant(4)
...     b = pf.constant(38)
...     x = a + b
... 
>>> graph(x)
42
```

**Comment by tillahoffmann** [comment]
@leepand, just to check: Are you using python2? The library only supports python3 at the moment.

**Comment by leepand** [comment]
@tillahoffmann thx for your response, I ran the code using python3.6 in virtualenv environment as following info:
Pandeng:pythonflow leepand$ source activate lepandpy3.0
(lepandpy3.0) Pandeng:pythonflow leepand$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythonflow as pf
>>> with pf.Graph() as graph:
...     a = pf.constant(4)
...     b = pf.constant(38)
...     x = a + b
...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/leepand/Downloads/BigRLab_APIs/flask_lab/pythonflow/pythonflow/core.py", line 329, in __add__
    return add(self, other, graph=self.graph)
  File "/Users/leepand/Downloads/BigRLab_APIs/flask_lab/pythonflow/pythonflow/core.py", line 480, in _wrapper
    return func_op(target, *args, **kwargs_inner, **kwargs)
  File "/Users/leepand/Downloads/BigRLab_APIs/flask_lab/pythonflow/pythonflow/core.py", line 458, in __init__
    super(func_op, self).__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'graph'
>>>

**Comment by tillahoffmann** [comment]
@leepand, do you have any way to reproduce this issue in a Docker container so I can have a look at it?
