### ISSUE TITLE
Unexpected(?) behaviour in `Graph.apply`

### ISSUE THREAD

**Issue by easyas314159** [spotify/pythonflow#43]
I ran into an issue today while attempting repeated evaluations of a graph. My rough usage pattern looks like this:

```python
context = {'a': 1, 'b': 2}
for df in frames:
	out = graph(outputs, context=context, frame=df)
```

Which worked fine for the first call but fails with the following error on the second call:

```python
ValueError: duplicate value for operation '<pf.placeholder 'first_input'>'
```

After some digging, I noticed that the `Graph.normalize_context` method modifies the `context` in-place. It is not mentioned in the documentation, and given the semantics of a `Graph.apply` this does not seem like an expected (or desired?) side-effect.

Is this something that should be updated in the documentation? Should `Graph.normalize_context` be modified to copy the context and not modify it in-place? Or is there a better pattern I should be using if I need to repeatedly call the graph object with some constant context and a handful of varying placeholders? (It probably wouldn't hurt to update the documentation with that pattern if there is one).

**Comment by tillahoffmann** [comment]
Yes, the modification of the context in place should be more well documented. The motivation for modifying the context in place is that the output of any operation can be inspected, e.g. for debugging purposes, by inspecting the modified context. 

I'll update the documentation in the next release or feel free to send a PR if you'd like to tackle it.

In the meantime, you can achieve your desired behaviour using a copy of the dictionary as so.

```python
context = {'a': 1, 'b': 2}
for df in frames:
	out = graph(outputs, context=context.copy(), frame=df)
```
