### ISSUE TITLE
Project inactive - any reason? 

### ISSUE THREAD

**Issue by mturok** [spotify/pythonflow#48]
Hi - looks like this project isn't active any longer (even though it accumulated 215 stars in short order ;-) ).

Any reason why?   The ideas behind it look quite powerful.

Best,
Michael

**Comment by tillahoffmann** [comment]
Hi Michael, apologies for the slow reply. The project is relatively inactive because we haven't had any immediate needs to update it. However, if you have specific ideas, contributions and issues are welcome.

**Comment by mturok** [comment]
No worries.   Have you been using this package, or is it mostly dormant?
